apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-vote.fullname" . }}-back
  labels:
  {{- include "azure-vote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.back.type }}
  selector:
    app: azure-vote-back
  {{- include "azure-vote.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.back.ports | toYaml | nindent 2 -}}