apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-vote.fullname" . }}-front
  labels:
  {{- include "azure-vote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.front.type }}
  selector:
    app: azure-vote-front
  {{- include "azure-vote.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.front.ports | toYaml | nindent 2 -}}