back:
  azureVoteBack:
    env:
      allowEmptyPassword: "yes"
    image:
      repository: mcr.microsoft.com/oss/bitnami/redis
      tag: 6.0.8
  nodeSelector:
    kubernetes.io/os: linux
  ports:
    - port: 6379
      targetPort: 0
  replicas: 1
  type: ClusterIP
front:
  azureVoteFront:
    env:
      redis: azure-vote-back
    image:
      repository: hemiacr.azurecr.io/azure-vote
      tag: v1
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 250m
  nodeSelector:
    beta.kubernetes.io/os: linux
  ports:
    - port: 80
      targetPort: 0
  replicas: 1
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
