name: Build Azure vote front
on:
  push:
    paths:
      - "azure-vote/**"
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image: azure-vote-front
          folder: azure-vote
          branch: master
          tag: ${{ github.sha }}
          # tag: v1
      # - name: Azure login
      #   uses: azure/login@v1.4.3
      #   with:
      #     creds: ${{ secrets.AZURESECRET }}

