name: Deploy Azure vote front
on: workflow_dispatch
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          creds: '${{ secrets.AZURESECRET }}'
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: hemiacr.azurecr.io
          username: hemiacr
          password: 8UsAN+ZtJDKDoM8f/Gdhfhutg3BmSVaEnBwVT8Baja+ACRB4XB2d
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.CLUSTER_NAME }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            azure-vote-all-in-one-redis.yaml
          images: '${{ secrets.REGISTRY}}/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}'
          # images: '${{ secrets.REGISTRY}}/${{ secrets.repository }}/azure-vote-front:v1'
          pull-images: false
